steps:
  - id: "Installing dependencies"
    name: "gcr.io/cloud-builders/go"
    args: ['install', 'soma']
    env:
      - GOPATH=.

  - id: "Running tests"
    name: "gcr.io/cloud-builders/go"
    args: ['test', 'soma']
    env:
      - GOPATH=.

  - id: "Build image"
    name: "gcr.io/cloud-builders/docker"
    args: ['build', '--tag=gcr.io/$PROJECT_ID/soma', '.']
    env:
      - GOPATH=.
 
images: ['gcr.io/$PROJECT_ID/soma']
